{
 "title": "Jenkins as Platform",
 "description": "Jobs queue speeds and rates, Executors availability, Nodes status, Jenkins and JVM resource usage, Jenkins Job Status, and lot more.",
 "tags": [
  "jenkins",
  "ci",
  "cicd"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "gauge",
   "description": "Quantidade de uso de CPU pela JVM",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vm_cpu_load{instance=\"jenkins.vrbeneficios.io:443\"}"
    }
   ]
  },
  {
   "title": "Memoria",
   "type": "gauge",
   "description": "Quantidade de memoria sendo utilizada dentro da JVM (limite 4GB)",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(vm_memory_total_used{instance=\"jenkins.vrbeneficios.io:443\"}/1000000000)"
    }
   ]
  },
  {
   "title": "Memoria livre",
   "type": "gauge",
   "description": "Quantidade de memoria disponivel dentro da JVM do jenkins",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(vm_memory_total_max{instance=\"jenkins.vrbeneficios.io:443\"} - vm_memory_total_used{instance=\"jenkins.vrbeneficios.io:443\"}) / vm_memory_total_max{instance=\"jenkins.vrbeneficios.io:443\"} * 100.0"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "prometheus_jenkins_up{instance=\"jenkins.vrbeneficios.io:443\"}"
    }
   ]
  },
  {
   "title": "Indisponibilidades",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "delta(http_responseCodes_serviceUnavailable_total{instance=\"jenkins.vrbeneficios.io:443\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Custo CI/CD",
   "type": "singlestat",
   "description": "Custo baseado na quantidade de agentes provisionados e no tempo de execução dentro do cluster dentro do prazo de um dia. Mais informações de como é gerado essa métrica em: http://confluence.vr.com.br/display/devtools/Jenkins",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "format": "currencyUSD",
   "valueName": "current",
   "targets": [
    {
     "expr": "((delta(jenkins_node_builds_count{instance=\"jenkins.vrbeneficios.io:443\",node=\"master\"}[$__interval])*0.27594) * 0.1)"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 2 },
   "format": "clockms",
   "valueName": "current",
   "targets": [
    {
     "expr": "prometheus_jenkins_uptime{instance=\"jenkins.vrbeneficios.io:443\"}"
    }
   ]
  },
  {
   "title": "Erros internos",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 15, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "delta(http_responseCodes_serverError_total{instance=\"jenkins.vrbeneficios.io:443\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Executores livres",
   "type": "stat",
   "description": "Quantidade de executores ociosos",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "delta(jenkins_executor_free_value{instance=\"jenkins.vrbeneficios.io:443\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Em espera",
   "type": "stat",
   "description": "Quantidade de jobs em fase de inicializacao",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jenkins_queue_size_value{instance=\"jenkins.vrbeneficios.io:443\"}"
    }
   ]
  },
  {
   "title": "Executando",
   "type": "stat",
   "description": "Total de jobs em execucao no momento",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jenkins_executor_in_use_value{instance=\"jenkins.vrbeneficios.io:443\"}"
    }
   ]
  },
  {
   "title": "Atualizações",
   "type": "stat",
   "description": "Quantidade de atualizações disponiveis",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jenkins_plugins_withUpdate{instance=\"jenkins.vrbeneficios.io:443\"}"
    }
   ]
  },
  {
   "title": "Disco usado jobs",
   "type": "singlestat",
   "description": "Quantidade de disco usada pelo master para os jobs",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 4 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "prometheus_jenkins_disk_usage_bytes{directory=\"JENKINS_HOME/workspace\", instance=\"jenkins.vrbeneficios.io:443\"}"
    }
   ]
  },
  {
   "title": "Disco usado por plugins",
   "type": "singlestat",
   "description": "Quantidade de disco usado pelo master para armazenar os plugins",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 4 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "prometheus_jenkins_disk_usage_bytes{directory=\"JENKINS_HOME/plugins\",instance=\"jenkins.vrbeneficios.io:443\"}"
    }
   ]
  },
  {
   "title": "Disco usado por logs",
   "type": "singlestat",
   "description": "Quantidade de disco usado para armazenar logs",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 4 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "prometheus_jenkins_disk_usage_bytes{directory=\"JENKINS_HOME/logs\", instance=\"jenkins.vrbeneficios.io:443\"}"
    }
   ]
  },
  {
   "title": "Tempo de inicializacao dos jobs na fila de espera",
   "type": "graph",
   "description": "Tempo médio de espera na inicialização de um build",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "s", "label": "Segundos" }
   ],
   "targets": [
    {
     "expr": "jenkins_job_queuing_duration{instance=\"jenkins.vrbeneficios.io:443\"}"
    }
   ]
  },
  {
   "title": "Taxa de sucesso dos builds do dia",
   "type": "piechart",
   "description": "Relação diária de builds e seus resultados",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(jenkins_runs_success_total{instance=\"jenkins.vrbeneficios.io:443\"}[$__rate_interval])",
     "legendFormat": "Sucesso"
    },
    {
     "expr": "delta(jenkins_runs_failure_total{instance=\"jenkins.vrbeneficios.io:443\"}[$__rate_interval])",
     "legendFormat": "Falha"
    },
    {
     "expr": "delta(jenkins_runs_aborted_total{instance=\"jenkins.vrbeneficios.io:443\"}[$__rate_interval])",
     "legendFormat": "Cancelados"
    },
    {
     "expr": "delta(jenkins_runs_unstable_total{instance=\"jenkins.vrbeneficios.io:443\"}[$__rate_interval])",
     "legendFormat": "Instaveis"
    }
   ]
  },
  {
   "title": "Execucoes do dia",
   "type": "bargauge",
   "description": "Relação diária de builds e seus resultados",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(jenkins_node_builds_count{instance=\"jenkins.vrbeneficios.io:443\", node=\"master\"}[$__rate_interval])",
     "legendFormat": "Total de builds"
    },
    {
     "expr": "delta(jenkins_runs_success_total{instance=\"jenkins.vrbeneficios.io:443\"}[$__rate_interval])",
     "legendFormat": "Builds com sucesso"
    },
    {
     "expr": "delta(jenkins_runs_failure_total{instance=\"jenkins.vrbeneficios.io:443\"}[$__rate_interval])",
     "legendFormat": "Builds com falha"
    },
    {
     "expr": "delta(jenkins_runs_aborted_total{instance=\"jenkins.vrbeneficios.io:443\"}[$__rate_interval])",
     "legendFormat": "Builds cancelados"
    },
    {
     "expr": "delta(jenkins_runs_unstable_total{instance=\"jenkins.vrbeneficios.io:443\"}[$__rate_interval])",
     "legendFormat": "Builds instaveis"
    }
   ]
  },
  {
   "title": "Top 10 repositórios com maior tempo de duracao",
   "type": "table",
   "description": "Ranking de repositorios com maior tempo de build",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sort_desc (topk ( 10, (avg(prometheus_jenkins_builds_last_build_duration_milliseconds{instance=\"jenkins.vrbeneficios.io:443\", repo!~\"packer|spikes-e-pocs|jenkins|.*-pipe\"}) by (repo) / 60000)))",
     "legendFormat": "{{repo}}"
    }
   ]
  },
  {
   "title": "Top 5 repositórios com maior numero de falhas",
   "type": "table-old",
   "description": "Ranking de repositorios com maior numero de falhas em builds",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sort_desc (topk (5, (sum(delta(prometheus_jenkins_builds_failed_build_count{instance=\"jenkins.vrbeneficios.io:443\", repo!~\"packer|spikes-e-pocs|.*-pipe\"}[$__rate_interval])) by (repo))))",
     "legendFormat": "{{repo}}"
    }
   ]
  },
  {
   "title": "Top 5 repositórios com maior numero de sucesso",
   "type": "table",
   "description": "Ranking de repositorios com maior numero de sucessos em builds",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sort_desc (topk (5, (sum(delta(prometheus_jenkins_builds_success_build_count{instance=\"jenkins.vrbeneficios.io:443\"}[$__rate_interval])) by (repo))))",
     "legendFormat": "{{repo}}"
    }
   ]
  }
 ]
}