{
 "title": "Kubernetes overview",
 "description": "Dados do cluster kubernetes baseados no node_exporter e no kube_state_metrics",
 "tags": [
  "node_exporter",
  "kube_state_metrics",
  "kubernetes",
  "prometheus"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Datasource", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Overall platform", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Eventos na API",
   "type": "graph",
   "description": "Exibe quantidade de eventos na API do kubernetes",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "events" } },
   "yaxes": [
    { "format": "events", "label": "CPU" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(delta(apiserver_watch_events_total{group!=\"\"}[10m])) by (group))",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "Dynatrace status",
   "type": "stat",
   "description": "Status geral dos componentes do dynatrace no cluster kubernetes",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_namespace_created{job=\"kube-state-metrics\", namespace=\"dynatrace\"} OR on() vector(0))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Alocação de pods",
   "type": "piechart",
   "description": "Relação Pods/Alocacao.\nO cluster se encontra saudável se a taxa de pods em execucão for menor que 50% do valor dos pods alocaveis.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_pods{job=\"kube-state-metrics\"}) - sum(kube_pod_status_phase{job=\"kube-state-metrics\",phase=\"Running\"})",
     "legendFormat": "Pods allocaveis"
    },
    {
     "expr": "sum(kube_pod_status_phase{job=\"kube-state-metrics\",phase=\"Running\"})",
     "legendFormat": "Pods executando"
    },
    {
     "expr": "sum(kube_pod_status_phase{job=\"kube-state-metrics\", phase=\"Failed\"})",
     "legendFormat": "Falhando"
    },
    {
     "expr": "sum(kube_pod_status_phase{job=\"kube-state-metrics\", phase=\"Pending\"})",
     "legendFormat": "Em espera"
    },
    {
     "expr": "sum(kube_pod_status_phase{job=\"kube-state-metrics\", phase=\"Succeeded\"})",
     "legendFormat": "Completados"
    },
    {
     "expr": "sum(kube_pod_status_phase{job=\"kube-state-metrics\", phase=\"Unknown\"})",
     "legendFormat": "Desconhecido"
    }
   ]
  },
  {
   "title": "Pods status",
   "type": "bargauge",
   "description": "Contagem de pods por status no cluster.",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum( sum(kube_pod_status_phase{job=\"kube-state-metrics\", phase=\"Running\"}) by (pod))",
     "legendFormat": "Running"
    },
    {
     "expr": "sum( sum(kube_pod_status_phase{job=\"kube-state-metrics\", phase=\"Failed\"}) by (pod))",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum( sum(kube_pod_status_phase{job=\"kube-state-metrics\", phase=\"Pending\"}) by (pod))",
     "legendFormat": "Pending"
    },
    {
     "expr": "sum( sum(kube_pod_status_phase{job=\"kube-state-metrics\", phase=\"Succeeded\"}) by (pod))",
     "legendFormat": "Completed"
    },
    {
     "expr": "sum( sum(kube_pod_status_phase{job=\"kube-state-metrics\", phase=\"Unknown\"}) by (pod))",
     "legendFormat": "Unknown"
    }
   ]
  },
  {
   "title": "Prometheus status",
   "type": "stat",
   "description": "Status dos coletores do prometheus no respectivo cluster kubernetes",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_target_scrape_pools_failed_total{job=\"prometheus\"}",
     "legendFormat": "Health"
    }
   ]
  },
  {
   "title": "Autoscaler status",
   "type": "stat",
   "description": "Status do cluster-autoscaler do respectivo cluster kubernetes",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(kube_deployment_status_condition{job=\"kube-state-metrics\", status=\"true\", namespace=\"kube-system\", deployment=\"cluster-autoscaler\", condition=\"Available\"} OR on() vector(0)) by (deployment)"
    }
   ]
  },
  {
   "title": "Maximo",
   "type": "stat",
   "description": "Maximo de pods alocaveis no cluster",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_pods{job=\"kube-state-metrics\"})",
     "legendFormat": "Maximo de pods alocaveis no cluster"
    }
   ]
  },
  {
   "title": "Executando",
   "type": "stat",
   "description": "Pods alocados no cluster",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{job=\"kube-state-metrics\",phase=\"Running\"})",
     "legendFormat": "Pods running"
    },
    {
     "expr": "sum(kube_node_status_allocatable_pods{job=\"kube-state-metrics\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Alocavel",
   "type": "stat",
   "description": "Espaços para pods restantes",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_pods{job=\"kube-state-metrics\"}) - sum(kube_pod_status_phase{job=\"kube-state-metrics\"})",
     "legendFormat": "Pods alocaveis"
    },
    {
     "expr": "sum(kube_node_status_allocatable_pods{job=\"kube-state-metrics\"})"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "table",
   "description": "Informações gerais sobre os workernodes do cluster",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    { "expr": "node_uname_info - 0", "legendFormat": "Hostname" },
    {
     "expr": "sum(time() - node_boot_time_seconds) by(instance)",
     "legendFormat": "Uptime"
    },
    {
     "expr": "count(node_cpu_seconds_total{mode='system'}) by (instance)",
     "legendFormat": "CPU total"
    },
    { "expr": "node_memory_MemTotal_bytes - 0", "legendFormat": "Memory total" },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / (node_memory_MemTotal_bytes)))* 100",
     "legendFormat": "Memory available"
    },
    {
     "expr": "max((node_filesystem_size_bytes{fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{fstype=~\"ext.?|xfs\"}) *100/(node_filesystem_avail_bytes {fstype=~\"ext.?|xfs\"}+(node_filesystem_size_bytes{fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{fstype=~\"ext.?|xfs\"})))by(instance)",
     "legendFormat": "Disk usage"
    },
    {
     "expr": "max(rate(node_disk_read_bytes_total[$__rate_interval])) by (instance)",
     "legendFormat": "Disk Read"
    },
    {
     "expr": "max(rate(node_disk_written_bytes_total[$__rate_interval])) by (instance)",
     "legendFormat": "Disk Write"
    },
    {
     "expr": "max(rate(node_network_receive_bytes_total[$__rate_interval])*8) by (instance)",
     "legendFormat": "Download"
    },
    {
     "expr": "max(rate(node_network_transmit_bytes_total[$__rate_interval])*8) by (instance)",
     "legendFormat": "Upload"
    }
   ]
  },
  { "title": "Under platform", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Top CPU pods",
   "type": "graph",
   "description": "Quantidade CPU usada por pod",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "milicore(s)" } },
   "yaxes": [
    { "format": "milicore(s)", "label": "CPU" }
   ],
   "targets": [
    {
     "expr": "sort_desc(avg(container_cpu_usage_seconds_total{pod!~\"^$|^cicd-.*$|^kube-.*$|.*-node-.*|^dyna.*$|^oneagent.*$|^docker-.*$|^job-runner.*$|^coredns.*$\"}) by (pod)) / 1000",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Top memory usage by pods",
   "type": "graph",
   "description": "Quantidade de memoria usada por pods",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sort_desc(avg(container_memory_usage_bytes{pod!~\"^$|^cicd-.*$|^kube-.*$|.*-node-.*|^dyna.*$|^oneagent.*$|^docker-.*$|^job-runner.*$|^coredns.*$\"}) by (pod))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Top processes by pods",
   "type": "graph",
   "description": "Procesos em execucao por pod",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "Processes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(container_processes{pod!~\"^$|^cicd-.*$|^kube-.*$|.*-node-.*|^dyna.*$|^oneagent.*$|^docker-.*$|^job-runner.*$|^coredns.*$\"}) by (pod))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Top network received by pods",
   "type": "graph",
   "description": "Quantidade de dados recebido por pods",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes", "label": "Network received" }
   ],
   "targets": [
    {
     "expr": "delta(container_network_receive_bytes_total{pod!~\"^$|^cicd-.*$|^kube-.*$|.*-node-.*|^dyna.*$|^oneagent.*$|^docker-.*$|^job-runner.*$|^coredns.*$\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Top network errors by pods",
   "type": "graph",
   "description": "Quantidade de erros de rede por pods",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "Network errors" }
   ],
   "targets": [
    {
     "expr": "delta(container_network_transmit_errors_total{pod!~\"^$|^cicd-.*$|^kube-.*$|.*-node-.*|^dyna.*$|^oneagent.*$|^docker-.*$|^job-runner.*$|^coredns.*$\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Top network transmit by pods",
   "type": "graph",
   "description": "Quantidade de dados enviados por pods",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes", "label": "Network transmited" }
   ],
   "targets": [
    {
     "expr": "delta(container_network_transmit_bytes_total{pod!~\"^$|^cicd-.*$|^kube-.*$|.*-node-.*|^dyna.*$|^oneagent.*$|^docker-.*$|^job-runner.*$|^coredns.*$\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}