apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
  finalizers:
  - kubernetes.io/pv-protection
  name: grafana-bvr
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 100Gi
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0e742c32e7ebafb0f::fsap-0f83c2627f6d23ad3
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: grafana-bvr
    namespace: grafana
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  volumeMode: Filesystem
